import Head from 'next/head'

import { Hero, Features, Info, Testimonials } from '@/components'

export async function getStaticProps() {
  const response = await fetch('http://localhost:3000/api/testimonials', {
    method: 'GET',
    credentials: 'same-origin'
  });
  const testimonials = await response.json();

  return {
    props: {
      testimonials
    }
  }
}

export default function Home({ testimonials }) {
  return (
    <>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Features />
      <Info />
      <Testimonials testimonials={testimonials} />
    </>
  )
}
