import Head from 'next/head'
import { PageHeader, Typography } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography tag="h1">Hello World</Typography>
    </>
  )
}
